# Generated by Django 2.2.5 on 2019-11-19 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='资产名称')),
                ('sn', models.CharField(max_length=100, verbose_name='资产编码')),
            ],
            options={
                'verbose_name': '资产总表',
                'verbose_name_plural': '资产总表',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='业务名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='业务编码')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Product', verbose_name='上级业务')),
            ],
            options={
                'verbose_name': '业务表',
                'verbose_name_plural': '业务表',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=150, verbose_name='主机名称')),
                ('public_ip', models.GenericIPAddressField(verbose_name='公网地址')),
                ('inside_ip', models.GenericIPAddressField(verbose_name='内网地址')),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Asset', verbose_name='资产名称')),
            ],
            options={
                'verbose_name': '服务器表',
                'verbose_name_plural': '服务器表',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='基础服务名称')),
                ('version', models.CharField(max_length=50, verbose_name='基础服务版本')),
                ('Server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Server', verbose_name='部署主机')),
            ],
            options={
                'verbose_name': '基础服务表',
                'verbose_name_plural': '基础服务表',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='项目名称')),
                ('code', models.CharField(blank=True, max_length=50, null=True, verbose_name='项目编码')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Product', verbose_name='所属业务线')),
            ],
            options={
                'verbose_name': '项目表',
                'verbose_name_plural': '项目表',
            },
        ),
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='应用服务名称')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project', verbose_name='所属项目')),
                ('server', models.ManyToManyField(to='cmdb.Server', verbose_name='部署主机')),
                ('service', models.ManyToManyField(to='cmdb.Service', verbose_name='依赖基础服务')),
            ],
            options={
                'verbose_name': '应用服务表',
                'verbose_name_plural': '应用服务表',
            },
        ),
    ]
