# Generated by Django 2.2.5 on 2019-11-19 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Product', verbose_name='上级业务'),
        ),
        migrations.AlterField(
            model_name='server',
            name='inside_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='内网地址'),
        ),
        migrations.AlterField(
            model_name='server',
            name='public_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='公网地址'),
        ),
    ]
