# Generated by Django 2.2.5 on 2019-11-23 19:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cmdb', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader', to=settings.AUTH_USER_MODEL, verbose_name='项目负责人'),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='项目成员'),
        ),
        migrations.AddField(
            model_name='project',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Product', verbose_name='所属业务线'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cmdb.Product', verbose_name='上级业务'),
        ),
        migrations.AlterUniqueTogether(
            name='env',
            unique_together={('name', 'code')},
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='cmdb.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='asset',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc', to='cmdb.IDC', verbose_name='所属机房'),
        ),
        migrations.AddField(
            model_name='app',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Project', verbose_name='所属项目'),
        ),
        migrations.AddField(
            model_name='app',
            name='server',
            field=models.ManyToManyField(to='cmdb.Server', verbose_name='部署主机'),
        ),
        migrations.AddField(
            model_name='app',
            name='service',
            field=models.ManyToManyField(to='cmdb.Service', verbose_name='依赖基础服务'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('product', 'name')},
        ),
    ]
