# Generated by Django 2.2.5 on 2019-11-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0002_auto_20191119_2152'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Server',
        ),
        migrations.AddField(
            model_name='service',
            name='Server',
            field=models.ManyToManyField(to='cmdb.Server', verbose_name='部署主机'),
        ),
    ]
