# Generated by Django 2.2.5 on 2019-11-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0004_auto_20191120_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app',
            name='app_type',
            field=models.SmallIntegerField(choices=[(0, 'base'), (1, 'api'), (2, 'web')], default=0, help_text='0:基础服务(base);1:api;2:web', verbose_name='应用类型'),
        ),
    ]
