# Generated by Django 2.2.5 on 2019-11-23 19:30

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], max_length=12, null=True)),
                ('phone', models.CharField(max_length=11, null=True, unique=True)),
                ('limit', models.IntegerField(blank=True, default=0, verbose_name='Login Limit')),
                ('login_date', models.DateTimeField(blank=True, null=True, verbose_name='Login By')),
                ('valid_date', models.DateTimeField(blank=True, null=True, verbose_name='Valid Date')),
                ('comment', models.CharField(blank=True, max_length=128, null=True, verbose_name='User Comment')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '用户表',
                'verbose_name_plural': '用户表',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='菜单名')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
                ('priority', models.IntegerField(blank=True, help_text='菜单的显示顺序，优先级越小显示越靠前', null=True, verbose_name='显示优先级')),
                ('is_show', models.BooleanField(blank=True, default=False, verbose_name='是否导航栏显示')),
                ('memu_level', models.SmallIntegerField(blank=True, default=1, verbose_name='菜单等级')),
                ('parent', models.ForeignKey(blank=True, help_text='如果添加的是子菜单，请选择父菜单', null=True, on_delete=True, to='rbac.Menu', verbose_name='父级菜单')),
            ],
            options={
                'verbose_name': '菜单表',
                'verbose_name_plural': '菜单表',
                'ordering': ['priority', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='权限名')),
                ('url', models.CharField(blank=True, help_text='是否给菜单设置一个url地址', max_length=300, null=True, verbose_name='权限url地址')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='权限图标')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='对应菜单')),
                ('parent', models.ForeignKey(blank=True, help_text='如果添加的是子权限，请选择父权限', null=True, on_delete=True, to='rbac.Permission', verbose_name='父级权限')),
            ],
            options={
                'verbose_name': '权限表',
                'verbose_name_plural': '权限表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='职位')),
                ('permission', models.ManyToManyField(to='rbac.Permission')),
            ],
            options={
                'verbose_name': '角色表',
                'verbose_name_plural': '角色表',
            },
        ),
        migrations.CreateModel(
            name='RequestRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ipaddr', models.GenericIPAddressField(verbose_name='Client Address')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Request Date Time')),
                ('type', models.IntegerField(choices=[(0, 'GET'), (1, 'POST')], verbose_name='Request Type')),
                ('get_full_path', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Request Full Path')),
                ('post_body', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Request Post Body')),
                ('username', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='UserName')),
            ],
            options={
                'verbose_name': 'Request Record',
                'verbose_name_plural': 'Request Record',
                'db_table': 'requestrecord',
            },
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(blank=True, to='rbac.Role'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
