# Generated by Django 2.2.5 on 2019-11-23 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='如果添加的是子菜单，请选择父菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='父级菜单'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='如果添加的是子权限，请选择父权限', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Permission', verbose_name='父级权限'),
        ),
    ]
