# Generated by Django 2.2.5 on 2019-11-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_auto_20191106_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_show',
            field=models.BooleanField(blank=True, default=False, verbose_name='是否导航栏显示'),
        ),
    ]
