# Generated by Django 2.2.5 on 2019-11-07 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_menu_is_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='memu_level',
            field=models.SmallIntegerField(blank=True, default=1, verbose_name='菜单等级'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.Menu', verbose_name='对应菜单'),
        ),
    ]
