# Generated by Django 2.2.5 on 2019-11-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_auto_20191108_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='role',
            field=models.ManyToManyField(blank=True, to='rbac.Role'),
        ),
    ]
