# Generated by Django 2.2.5 on 2019-11-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_requestrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='limit',
            field=models.IntegerField(blank=True, default=0, verbose_name='Login Limit'),
        ),
    ]
